# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageUser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageUser.proto',
  package='Message',
  serialized_pb=_b('\n\x11MessageUser.proto\x12\x07Message\"V\n\tUserLogin\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06ticket\x18\x02 \x01(\t\x12\r\n\x05world\x18\x03 \x01(\x05\x12\x0e\n\x06socket\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\x05\";\n\nGuestLogin\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\r\n\x05world\x18\x02 \x01(\x05\x12\x0e\n\x06socket\x18\x03 \x01(\x05\"\'\n\x0bPlayerLogin\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\"\x19\n\nUserLogout\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x19\n\nUserCreate\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x1b\n\x0cUserDisplace\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x1f\n\x10UserHeartRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"\"\n\x11UserHeartResponse\x12\r\n\x05stime\x18\x01 \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERLOGIN = _descriptor.Descriptor(
  name='UserLogin',
  full_name='Message.UserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.UserLogin.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='Message.UserLogin.ticket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Message.UserLogin.world', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='socket', full_name='Message.UserLogin.socket', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='Message.UserLogin.error', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=116,
)


_GUESTLOGIN = _descriptor.Descriptor(
  name='GuestLogin',
  full_name='Message.GuestLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='Message.GuestLogin.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Message.GuestLogin.world', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='socket', full_name='Message.GuestLogin.socket', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=177,
)


_PLAYERLOGIN = _descriptor.Descriptor(
  name='PlayerLogin',
  full_name='Message.PlayerLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.PlayerLogin.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.PlayerLogin.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=218,
)


_USERLOGOUT = _descriptor.Descriptor(
  name='UserLogout',
  full_name='Message.UserLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.UserLogout.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=245,
)


_USERCREATE = _descriptor.Descriptor(
  name='UserCreate',
  full_name='Message.UserCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.UserCreate.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=272,
)


_USERDISPLACE = _descriptor.Descriptor(
  name='UserDisplace',
  full_name='Message.UserDisplace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.UserDisplace.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=301,
)


_USERHEARTREQUEST = _descriptor.Descriptor(
  name='UserHeartRequest',
  full_name='Message.UserHeartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.UserHeartRequest.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=334,
)


_USERHEARTRESPONSE = _descriptor.Descriptor(
  name='UserHeartResponse',
  full_name='Message.UserHeartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stime', full_name='Message.UserHeartResponse.stime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=370,
)

DESCRIPTOR.message_types_by_name['UserLogin'] = _USERLOGIN
DESCRIPTOR.message_types_by_name['GuestLogin'] = _GUESTLOGIN
DESCRIPTOR.message_types_by_name['PlayerLogin'] = _PLAYERLOGIN
DESCRIPTOR.message_types_by_name['UserLogout'] = _USERLOGOUT
DESCRIPTOR.message_types_by_name['UserCreate'] = _USERCREATE
DESCRIPTOR.message_types_by_name['UserDisplace'] = _USERDISPLACE
DESCRIPTOR.message_types_by_name['UserHeartRequest'] = _USERHEARTREQUEST
DESCRIPTOR.message_types_by_name['UserHeartResponse'] = _USERHEARTRESPONSE

UserLogin = _reflection.GeneratedProtocolMessageType('UserLogin', (_message.Message,), dict(
  DESCRIPTOR = _USERLOGIN,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserLogin)
  ))
_sym_db.RegisterMessage(UserLogin)

GuestLogin = _reflection.GeneratedProtocolMessageType('GuestLogin', (_message.Message,), dict(
  DESCRIPTOR = _GUESTLOGIN,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.GuestLogin)
  ))
_sym_db.RegisterMessage(GuestLogin)

PlayerLogin = _reflection.GeneratedProtocolMessageType('PlayerLogin', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERLOGIN,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.PlayerLogin)
  ))
_sym_db.RegisterMessage(PlayerLogin)

UserLogout = _reflection.GeneratedProtocolMessageType('UserLogout', (_message.Message,), dict(
  DESCRIPTOR = _USERLOGOUT,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserLogout)
  ))
_sym_db.RegisterMessage(UserLogout)

UserCreate = _reflection.GeneratedProtocolMessageType('UserCreate', (_message.Message,), dict(
  DESCRIPTOR = _USERCREATE,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserCreate)
  ))
_sym_db.RegisterMessage(UserCreate)

UserDisplace = _reflection.GeneratedProtocolMessageType('UserDisplace', (_message.Message,), dict(
  DESCRIPTOR = _USERDISPLACE,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserDisplace)
  ))
_sym_db.RegisterMessage(UserDisplace)

UserHeartRequest = _reflection.GeneratedProtocolMessageType('UserHeartRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERHEARTREQUEST,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserHeartRequest)
  ))
_sym_db.RegisterMessage(UserHeartRequest)

UserHeartResponse = _reflection.GeneratedProtocolMessageType('UserHeartResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERHEARTRESPONSE,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.UserHeartResponse)
  ))
_sym_db.RegisterMessage(UserHeartResponse)


# @@protoc_insertion_point(module_scope)
