# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageItem.proto',
  package='Message',
  serialized_pb=_b('\n\x11MessageItem.proto\x12\x07Message\"\x87\x01\n\x0cItemGainSync\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\x12\x12\n\ntemplateid\x18\x02 \x01(\x05\x12\r\n\x05stack\x18\x03 \x01(\x05\x12\x10\n\x08position\x18\x04 \x01(\x05\x12\x0e\n\x06parent\x18\x05 \x01(\x03\x12\x0f\n\x07\x65quipid\x18\x06 \x01(\x03\x12\x11\n\tintensify\x18\x07 \x01(\x05\" \n\x0eItemDeleteSync\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\" \n\x0eItemUseRequest\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\"#\n\x11ItemDeleteRequest\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\"!\n\x0fItemSellRequest\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\"2\n\x10ItemEquipRequest\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\x12\x0e\n\x06roleid\x18\x02 \x01(\x03\"F\n\x12ItemUnequipRequest\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\x12\x0e\n\x06roleid\x18\x02 \x01(\x03\x12\x10\n\x08position\x18\x03 \x01(\x05\"\xa8\x01\n\x0cItemAttrSync\x12\x0e\n\x06itemid\x18\x01 \x01(\x03\x12(\n\x04\x61ttr\x18\x02 \x03(\x0b\x32\x1a.Message.ItemAttrSync.Attr\x1a^\n\x04\x41ttr\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05group\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05val32\x18\x04 \x01(\x05\x12\r\n\x05val64\x18\x05 \x01(\x03\x12\x0e\n\x06valstr\x18\x06 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEMGAINSYNC = _descriptor.Descriptor(
  name='ItemGainSync',
  full_name='Message.ItemGainSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemGainSync.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='templateid', full_name='Message.ItemGainSync.templateid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack', full_name='Message.ItemGainSync.stack', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='Message.ItemGainSync.position', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='Message.ItemGainSync.parent', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equipid', full_name='Message.ItemGainSync.equipid', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensify', full_name='Message.ItemGainSync.intensify', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=166,
)


_ITEMDELETESYNC = _descriptor.Descriptor(
  name='ItemDeleteSync',
  full_name='Message.ItemDeleteSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemDeleteSync.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=200,
)


_ITEMUSEREQUEST = _descriptor.Descriptor(
  name='ItemUseRequest',
  full_name='Message.ItemUseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemUseRequest.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=234,
)


_ITEMDELETEREQUEST = _descriptor.Descriptor(
  name='ItemDeleteRequest',
  full_name='Message.ItemDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemDeleteRequest.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=271,
)


_ITEMSELLREQUEST = _descriptor.Descriptor(
  name='ItemSellRequest',
  full_name='Message.ItemSellRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemSellRequest.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=306,
)


_ITEMEQUIPREQUEST = _descriptor.Descriptor(
  name='ItemEquipRequest',
  full_name='Message.ItemEquipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemEquipRequest.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roleid', full_name='Message.ItemEquipRequest.roleid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=358,
)


_ITEMUNEQUIPREQUEST = _descriptor.Descriptor(
  name='ItemUnequipRequest',
  full_name='Message.ItemUnequipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemUnequipRequest.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roleid', full_name='Message.ItemUnequipRequest.roleid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='Message.ItemUnequipRequest.position', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=430,
)


_ITEMATTRSYNC_ATTR = _descriptor.Descriptor(
  name='Attr',
  full_name='Message.ItemAttrSync.Attr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.ItemAttrSync.Attr.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group', full_name='Message.ItemAttrSync.Attr.group', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='Message.ItemAttrSync.Attr.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val32', full_name='Message.ItemAttrSync.Attr.val32', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val64', full_name='Message.ItemAttrSync.Attr.val64', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valstr', full_name='Message.ItemAttrSync.Attr.valstr', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=601,
)

_ITEMATTRSYNC = _descriptor.Descriptor(
  name='ItemAttrSync',
  full_name='Message.ItemAttrSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='Message.ItemAttrSync.itemid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='Message.ItemAttrSync.attr', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ITEMATTRSYNC_ATTR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=601,
)

_ITEMATTRSYNC_ATTR.containing_type = _ITEMATTRSYNC
_ITEMATTRSYNC.fields_by_name['attr'].message_type = _ITEMATTRSYNC_ATTR
DESCRIPTOR.message_types_by_name['ItemGainSync'] = _ITEMGAINSYNC
DESCRIPTOR.message_types_by_name['ItemDeleteSync'] = _ITEMDELETESYNC
DESCRIPTOR.message_types_by_name['ItemUseRequest'] = _ITEMUSEREQUEST
DESCRIPTOR.message_types_by_name['ItemDeleteRequest'] = _ITEMDELETEREQUEST
DESCRIPTOR.message_types_by_name['ItemSellRequest'] = _ITEMSELLREQUEST
DESCRIPTOR.message_types_by_name['ItemEquipRequest'] = _ITEMEQUIPREQUEST
DESCRIPTOR.message_types_by_name['ItemUnequipRequest'] = _ITEMUNEQUIPREQUEST
DESCRIPTOR.message_types_by_name['ItemAttrSync'] = _ITEMATTRSYNC

ItemGainSync = _reflection.GeneratedProtocolMessageType('ItemGainSync', (_message.Message,), dict(
  DESCRIPTOR = _ITEMGAINSYNC,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemGainSync)
  ))
_sym_db.RegisterMessage(ItemGainSync)

ItemDeleteSync = _reflection.GeneratedProtocolMessageType('ItemDeleteSync', (_message.Message,), dict(
  DESCRIPTOR = _ITEMDELETESYNC,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemDeleteSync)
  ))
_sym_db.RegisterMessage(ItemDeleteSync)

ItemUseRequest = _reflection.GeneratedProtocolMessageType('ItemUseRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMUSEREQUEST,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemUseRequest)
  ))
_sym_db.RegisterMessage(ItemUseRequest)

ItemDeleteRequest = _reflection.GeneratedProtocolMessageType('ItemDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMDELETEREQUEST,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemDeleteRequest)
  ))
_sym_db.RegisterMessage(ItemDeleteRequest)

ItemSellRequest = _reflection.GeneratedProtocolMessageType('ItemSellRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMSELLREQUEST,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemSellRequest)
  ))
_sym_db.RegisterMessage(ItemSellRequest)

ItemEquipRequest = _reflection.GeneratedProtocolMessageType('ItemEquipRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMEQUIPREQUEST,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemEquipRequest)
  ))
_sym_db.RegisterMessage(ItemEquipRequest)

ItemUnequipRequest = _reflection.GeneratedProtocolMessageType('ItemUnequipRequest', (_message.Message,), dict(
  DESCRIPTOR = _ITEMUNEQUIPREQUEST,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemUnequipRequest)
  ))
_sym_db.RegisterMessage(ItemUnequipRequest)

ItemAttrSync = _reflection.GeneratedProtocolMessageType('ItemAttrSync', (_message.Message,), dict(

  Attr = _reflection.GeneratedProtocolMessageType('Attr', (_message.Message,), dict(
    DESCRIPTOR = _ITEMATTRSYNC_ATTR,
    __module__ = 'MessageItem_pb2'
    # @@protoc_insertion_point(class_scope:Message.ItemAttrSync.Attr)
    ))
  ,
  DESCRIPTOR = _ITEMATTRSYNC,
  __module__ = 'MessageItem_pb2'
  # @@protoc_insertion_point(class_scope:Message.ItemAttrSync)
  ))
_sym_db.RegisterMessage(ItemAttrSync)
_sym_db.RegisterMessage(ItemAttrSync.Attr)


# @@protoc_insertion_point(module_scope)
