# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTypeDefine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageTypeDefine.proto',
  package='Message',
  serialized_pb=_b('\n\x17MessageTypeDefine.proto\x12\x07Message*\x84\x06\n\tMsgDefine\x12\x14\n\x10MSG_SERVER_BEGIN\x10\x00\x12\x19\n\x15MSG_SERVER_NET_ACCEPT\x10\x01\x12\x1a\n\x16MSG_SERVER_NET_CONNECT\x10\x02\x12\x18\n\x14MSG_SERVER_NET_CLOSE\x10\x03\x12\x1a\n\x16MSG_SERVER_NET_RESPONE\x10\x04\x12\x17\n\x13MSG_SERVER_REGISTER\x10\n\x12\x16\n\x12MSG_SERVER_REQUEST\x10\x0b\x12\x17\n\x13MSG_SERVER_RESPONSE\x10\x0c\x12\x14\n\x10MSG_COMMON_ERROR\x10\x64\x12\x14\n\x10MSG_COMMON_EVENT\x10\x65\x12\x1c\n\x17MSG_USER_LOGIN_RESPONSE\x10\xac\x02\x12\x1c\n\x17MSG_USER_HEART_RESPONSE\x10\xad\x02\x12\x1a\n\x15MSG_USER_LOGIN_PLAYER\x10\xae\x02\x12\x14\n\x0eMSG_SERVER_END\x10\xaf\xea\x01\x12\x16\n\x10MSG_CLIENT_BEGIN\x10\xb0\xea\x01\x12\x1c\n\x16MSG_REQUEST_USER_CHECK\x10\xb1\xea\x01\x12\x1d\n\x17MSG_REQUEST_GUEST_CHECK\x10\xb2\xea\x01\x12\x1d\n\x17MSG_REQUEST_USER_LOGOUT\x10\xb3\xea\x01\x12\x1d\n\x17MSG_REQUEST_USER_CREATE\x10\xb4\xea\x01\x12\x1c\n\x16MSG_REQUEST_USER_HEART\x10\xb5\xea\x01\x12\x1a\n\x14MSG_REQUEST_ITEM_USE\x10\x94\xeb\x01\x12\x1d\n\x17MSG_REQUEST_ITEM_DELETE\x10\x95\xeb\x01\x12\x1b\n\x15MSG_REQUEST_ITEM_SELL\x10\x96\xeb\x01\x12\x1c\n\x16MSG_REQUEST_ITEM_EQUIP\x10\x97\xeb\x01\x12\x1e\n\x18MSG_REQUEST_ITEM_UNEQUIP\x10\x98\xeb\x01\x12\x17\n\x11MSG_REQUEST_DEBUG\x10\xe0\xd4\x03\x12\x1a\n\x14MSG_REQUEST_NET_TEST\x10\xe1\xd4\x03\x12\x14\n\x0eMSG_CLIENT_END\x10\xff\xff\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGDEFINE = _descriptor.EnumDescriptor(
  name='MsgDefine',
  full_name='Message.MsgDefine',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_NET_ACCEPT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_NET_CONNECT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_NET_CLOSE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_NET_RESPONE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_REGISTER', index=5, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_REQUEST', index=6, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_RESPONSE', index=7, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_COMMON_ERROR', index=8, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_COMMON_EVENT', index=9, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_USER_LOGIN_RESPONSE', index=10, number=300,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_USER_HEART_RESPONSE', index=11, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_USER_LOGIN_PLAYER', index=12, number=302,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_SERVER_END', index=13, number=29999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_CLIENT_BEGIN', index=14, number=30000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_USER_CHECK', index=15, number=30001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_GUEST_CHECK', index=16, number=30002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_USER_LOGOUT', index=17, number=30003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_USER_CREATE', index=18, number=30004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_USER_HEART', index=19, number=30005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_ITEM_USE', index=20, number=30100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_ITEM_DELETE', index=21, number=30101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_ITEM_SELL', index=22, number=30102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_ITEM_EQUIP', index=23, number=30103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_ITEM_UNEQUIP', index=24, number=30104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_DEBUG', index=25, number=60000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_REQUEST_NET_TEST', index=26, number=60001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_CLIENT_END', index=27, number=65535,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=37,
  serialized_end=809,
)
_sym_db.RegisterEnumDescriptor(_MSGDEFINE)

MsgDefine = enum_type_wrapper.EnumTypeWrapper(_MSGDEFINE)
MSG_SERVER_BEGIN = 0
MSG_SERVER_NET_ACCEPT = 1
MSG_SERVER_NET_CONNECT = 2
MSG_SERVER_NET_CLOSE = 3
MSG_SERVER_NET_RESPONE = 4
MSG_SERVER_REGISTER = 10
MSG_SERVER_REQUEST = 11
MSG_SERVER_RESPONSE = 12
MSG_COMMON_ERROR = 100
MSG_COMMON_EVENT = 101
MSG_USER_LOGIN_RESPONSE = 300
MSG_USER_HEART_RESPONSE = 301
MSG_USER_LOGIN_PLAYER = 302
MSG_SERVER_END = 29999
MSG_CLIENT_BEGIN = 30000
MSG_REQUEST_USER_CHECK = 30001
MSG_REQUEST_GUEST_CHECK = 30002
MSG_REQUEST_USER_LOGOUT = 30003
MSG_REQUEST_USER_CREATE = 30004
MSG_REQUEST_USER_HEART = 30005
MSG_REQUEST_ITEM_USE = 30100
MSG_REQUEST_ITEM_DELETE = 30101
MSG_REQUEST_ITEM_SELL = 30102
MSG_REQUEST_ITEM_EQUIP = 30103
MSG_REQUEST_ITEM_UNEQUIP = 30104
MSG_REQUEST_DEBUG = 60000
MSG_REQUEST_NET_TEST = 60001
MSG_CLIENT_END = 65535


DESCRIPTOR.enum_types_by_name['MsgDefine'] = _MSGDEFINE


# @@protoc_insertion_point(module_scope)
