# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DBObject.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DBObject.proto',
  package='DBObj',
  serialized_pb=_b('\n\x0e\x44\x42Object.proto\x12\x05\x44\x42Obj\"\x9b\x02\n\x06\x44\x42User\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06openid\x18\x02 \x01(\t\x12\x11\n\tlogintime\x18\x03 \x01(\t\x12\x12\n\nlogouttime\x18\x04 \x01(\t\x12\x12\n\ncreatetime\x18\x05 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x07 \x01(\t\x12\x12\n\nlastplayer\x18\x08 \x01(\x03\x12,\n\nplayerlist\x18\t \x03(\x0b\x32\x18.DBObj.DBUser.PlayerInfo\x1aX\n\nPlayerInfo\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\x05\x12\x10\n\x08vocation\x18\x04 \x01(\x05\x12\r\n\x05level\x18\x05 \x01(\x05\"\x0e\n\x0c\x44\x42PlayerAttr\"!\n\x06\x44\x42Prop\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03tid\x18\x02 \x01(\x05\"\xd5\x01\n\x08\x44\x42Player\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x12\n\ncreatetime\x18\x02 \x01(\t\x12\x11\n\tlogintime\x18\x03 \x01(\t\x12\x12\n\nlogouttime\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\x05\x12\x10\n\x08vocation\x18\x07 \x01(\x05\x12\r\n\x05level\x18\x08 \x01(\x05\x12!\n\x04\x61ttr\x18\x14 \x01(\x0b\x32\x13.DBObj.DBPlayerAttr\x12\x1f\n\x08proplist\x18\x15 \x03(\x0b\x32\r.DBObj.DBProp')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DBUSER_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='DBObj.DBUser.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='DBObj.DBUser.PlayerInfo.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DBObj.DBUser.PlayerInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='DBObj.DBUser.PlayerInfo.gender', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='DBObj.DBUser.PlayerInfo.vocation', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='DBObj.DBUser.PlayerInfo.level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=309,
)

_DBUSER = _descriptor.Descriptor(
  name='DBUser',
  full_name='DBObj.DBUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='DBObj.DBUser.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid', full_name='DBObj.DBUser.openid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logintime', full_name='DBObj.DBUser.logintime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logouttime', full_name='DBObj.DBUser.logouttime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='DBObj.DBUser.createtime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='DBObj.DBUser.channel', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='DBObj.DBUser.addr', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastplayer', full_name='DBObj.DBUser.lastplayer', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerlist', full_name='DBObj.DBUser.playerlist', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DBUSER_PLAYERINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=309,
)


_DBPLAYERATTR = _descriptor.Descriptor(
  name='DBPlayerAttr',
  full_name='DBObj.DBPlayerAttr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=325,
)


_DBPROP = _descriptor.Descriptor(
  name='DBProp',
  full_name='DBObj.DBProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DBObj.DBProp.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='DBObj.DBProp.tid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=360,
)


_DBPLAYER = _descriptor.Descriptor(
  name='DBPlayer',
  full_name='DBObj.DBPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='DBObj.DBPlayer.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='DBObj.DBPlayer.createtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logintime', full_name='DBObj.DBPlayer.logintime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logouttime', full_name='DBObj.DBPlayer.logouttime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DBObj.DBPlayer.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='DBObj.DBPlayer.gender', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='DBObj.DBPlayer.vocation', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='DBObj.DBPlayer.level', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='DBObj.DBPlayer.attr', index=8,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proplist', full_name='DBObj.DBPlayer.proplist', index=9,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=576,
)

_DBUSER_PLAYERINFO.containing_type = _DBUSER
_DBUSER.fields_by_name['playerlist'].message_type = _DBUSER_PLAYERINFO
_DBPLAYER.fields_by_name['attr'].message_type = _DBPLAYERATTR
_DBPLAYER.fields_by_name['proplist'].message_type = _DBPROP
DESCRIPTOR.message_types_by_name['DBUser'] = _DBUSER
DESCRIPTOR.message_types_by_name['DBPlayerAttr'] = _DBPLAYERATTR
DESCRIPTOR.message_types_by_name['DBProp'] = _DBPROP
DESCRIPTOR.message_types_by_name['DBPlayer'] = _DBPLAYER

DBUser = _reflection.GeneratedProtocolMessageType('DBUser', (_message.Message,), dict(

  PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), dict(
    DESCRIPTOR = _DBUSER_PLAYERINFO,
    __module__ = 'DBObject_pb2'
    # @@protoc_insertion_point(class_scope:DBObj.DBUser.PlayerInfo)
    ))
  ,
  DESCRIPTOR = _DBUSER,
  __module__ = 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBUser)
  ))
_sym_db.RegisterMessage(DBUser)
_sym_db.RegisterMessage(DBUser.PlayerInfo)

DBPlayerAttr = _reflection.GeneratedProtocolMessageType('DBPlayerAttr', (_message.Message,), dict(
  DESCRIPTOR = _DBPLAYERATTR,
  __module__ = 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBPlayerAttr)
  ))
_sym_db.RegisterMessage(DBPlayerAttr)

DBProp = _reflection.GeneratedProtocolMessageType('DBProp', (_message.Message,), dict(
  DESCRIPTOR = _DBPROP,
  __module__ = 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBProp)
  ))
_sym_db.RegisterMessage(DBProp)

DBPlayer = _reflection.GeneratedProtocolMessageType('DBPlayer', (_message.Message,), dict(
  DESCRIPTOR = _DBPLAYER,
  __module__ = 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBPlayer)
  ))
_sym_db.RegisterMessage(DBPlayer)


# @@protoc_insertion_point(module_scope)
