# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageProp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageProp.proto',
  package='Message',
  serialized_pb=_b('\n\x11MessageProp.proto\x12\x07Message\"Q\n\x08PropData\x12\x0b\n\x03iid\x18\x01 \x01(\x03\x12\x0b\n\x03tid\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0e\n\x06\x65xpiry\x18\x04 \x01(\x03\x12\x0c\n\x04\x62ind\x18\x05 \x01(\x08\"2\n\x0bS2CPropList\x12#\n\x08proplist\x18\x01 \x03(\x0b\x32\x11.Message.PropData\"\x19\n\nC2SPropUse\x12\x0b\n\x03iid\x18\x01 \x01(\x03\"*\n\nC2SPropBuy\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x1a\n\x0b\x43\x32SPropSell\x12\x0b\n\x03iid\x18\x01 \x01(\x03\"\x1d\n\x0e\x43\x32SPropCompose\x12\x0b\n\x03iid\x18\x01 \x01(\x03\"\x1f\n\x10\x43\x32SPropDecompose\x12\x0b\n\x03iid\x18\x01 \x01(\x03\"\x1b\n\x0c\x43\x32SPropEquip\x12\x0b\n\x03iid\x18\x01 \x01(\x03\"\x1d\n\x0e\x43\x32SPropUnequip\x12\x0b\n\x03iid\x18\x01 \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROPDATA = _descriptor.Descriptor(
  name='PropData',
  full_name='Message.PropData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.PropData.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='Message.PropData.tid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Message.PropData.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='Message.PropData.expiry', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bind', full_name='Message.PropData.bind', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=111,
)


_S2CPROPLIST = _descriptor.Descriptor(
  name='S2CPropList',
  full_name='Message.S2CPropList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proplist', full_name='Message.S2CPropList.proplist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=163,
)


_C2SPROPUSE = _descriptor.Descriptor(
  name='C2SPropUse',
  full_name='Message.C2SPropUse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropUse.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=190,
)


_C2SPROPBUY = _descriptor.Descriptor(
  name='C2SPropBuy',
  full_name='Message.C2SPropBuy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Message.C2SPropBuy.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Message.C2SPropBuy.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=234,
)


_C2SPROPSELL = _descriptor.Descriptor(
  name='C2SPropSell',
  full_name='Message.C2SPropSell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropSell.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=262,
)


_C2SPROPCOMPOSE = _descriptor.Descriptor(
  name='C2SPropCompose',
  full_name='Message.C2SPropCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropCompose.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=293,
)


_C2SPROPDECOMPOSE = _descriptor.Descriptor(
  name='C2SPropDecompose',
  full_name='Message.C2SPropDecompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropDecompose.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=326,
)


_C2SPROPEQUIP = _descriptor.Descriptor(
  name='C2SPropEquip',
  full_name='Message.C2SPropEquip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropEquip.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=355,
)


_C2SPROPUNEQUIP = _descriptor.Descriptor(
  name='C2SPropUnequip',
  full_name='Message.C2SPropUnequip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iid', full_name='Message.C2SPropUnequip.iid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=386,
)

_S2CPROPLIST.fields_by_name['proplist'].message_type = _PROPDATA
DESCRIPTOR.message_types_by_name['PropData'] = _PROPDATA
DESCRIPTOR.message_types_by_name['S2CPropList'] = _S2CPROPLIST
DESCRIPTOR.message_types_by_name['C2SPropUse'] = _C2SPROPUSE
DESCRIPTOR.message_types_by_name['C2SPropBuy'] = _C2SPROPBUY
DESCRIPTOR.message_types_by_name['C2SPropSell'] = _C2SPROPSELL
DESCRIPTOR.message_types_by_name['C2SPropCompose'] = _C2SPROPCOMPOSE
DESCRIPTOR.message_types_by_name['C2SPropDecompose'] = _C2SPROPDECOMPOSE
DESCRIPTOR.message_types_by_name['C2SPropEquip'] = _C2SPROPEQUIP
DESCRIPTOR.message_types_by_name['C2SPropUnequip'] = _C2SPROPUNEQUIP

PropData = _reflection.GeneratedProtocolMessageType('PropData', (_message.Message,), dict(
  DESCRIPTOR = _PROPDATA,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.PropData)
  ))
_sym_db.RegisterMessage(PropData)

S2CPropList = _reflection.GeneratedProtocolMessageType('S2CPropList', (_message.Message,), dict(
  DESCRIPTOR = _S2CPROPLIST,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CPropList)
  ))
_sym_db.RegisterMessage(S2CPropList)

C2SPropUse = _reflection.GeneratedProtocolMessageType('C2SPropUse', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPUSE,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropUse)
  ))
_sym_db.RegisterMessage(C2SPropUse)

C2SPropBuy = _reflection.GeneratedProtocolMessageType('C2SPropBuy', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPBUY,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropBuy)
  ))
_sym_db.RegisterMessage(C2SPropBuy)

C2SPropSell = _reflection.GeneratedProtocolMessageType('C2SPropSell', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPSELL,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropSell)
  ))
_sym_db.RegisterMessage(C2SPropSell)

C2SPropCompose = _reflection.GeneratedProtocolMessageType('C2SPropCompose', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPCOMPOSE,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropCompose)
  ))
_sym_db.RegisterMessage(C2SPropCompose)

C2SPropDecompose = _reflection.GeneratedProtocolMessageType('C2SPropDecompose', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPDECOMPOSE,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropDecompose)
  ))
_sym_db.RegisterMessage(C2SPropDecompose)

C2SPropEquip = _reflection.GeneratedProtocolMessageType('C2SPropEquip', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPEQUIP,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropEquip)
  ))
_sym_db.RegisterMessage(C2SPropEquip)

C2SPropUnequip = _reflection.GeneratedProtocolMessageType('C2SPropUnequip', (_message.Message,), dict(
  DESCRIPTOR = _C2SPROPUNEQUIP,
  __module__ = 'MessageProp_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPropUnequip)
  ))
_sym_db.RegisterMessage(C2SPropUnequip)


# @@protoc_insertion_point(module_scope)
