# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageFriend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageFriend.proto',
  package='Message',
  serialized_pb=_b('\n\x13MessageFriend.proto\x12\x07Message\"h\n\nFriendData\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\x05\x12\x10\n\x08vocation\x18\x04 \x01(\x05\x12\r\n\x05level\x18\x05 \x01(\x05\x12\x0e\n\x06online\x18\x06 \x01(\x08\"8\n\rS2CFriendList\x12\'\n\nfriendlist\x18\x01 \x03(\x0b\x32\x13.Message.FriendData\"\x1b\n\x0c\x43\x32SAddFriend\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"\x1e\n\x0f\x43\x32SDeleteFriend\x12\x0b\n\x03pid\x18\x01 \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FRIENDDATA = _descriptor.Descriptor(
  name='FriendData',
  full_name='Message.FriendData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.FriendData.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.FriendData.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='Message.FriendData.gender', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='Message.FriendData.vocation', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Message.FriendData.level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='online', full_name='Message.FriendData.online', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=136,
)


_S2CFRIENDLIST = _descriptor.Descriptor(
  name='S2CFriendList',
  full_name='Message.S2CFriendList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friendlist', full_name='Message.S2CFriendList.friendlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=194,
)


_C2SADDFRIEND = _descriptor.Descriptor(
  name='C2SAddFriend',
  full_name='Message.C2SAddFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.C2SAddFriend.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=223,
)


_C2SDELETEFRIEND = _descriptor.Descriptor(
  name='C2SDeleteFriend',
  full_name='Message.C2SDeleteFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.C2SDeleteFriend.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=255,
)

_S2CFRIENDLIST.fields_by_name['friendlist'].message_type = _FRIENDDATA
DESCRIPTOR.message_types_by_name['FriendData'] = _FRIENDDATA
DESCRIPTOR.message_types_by_name['S2CFriendList'] = _S2CFRIENDLIST
DESCRIPTOR.message_types_by_name['C2SAddFriend'] = _C2SADDFRIEND
DESCRIPTOR.message_types_by_name['C2SDeleteFriend'] = _C2SDELETEFRIEND

FriendData = _reflection.GeneratedProtocolMessageType('FriendData', (_message.Message,), dict(
  DESCRIPTOR = _FRIENDDATA,
  __module__ = 'MessageFriend_pb2'
  # @@protoc_insertion_point(class_scope:Message.FriendData)
  ))
_sym_db.RegisterMessage(FriendData)

S2CFriendList = _reflection.GeneratedProtocolMessageType('S2CFriendList', (_message.Message,), dict(
  DESCRIPTOR = _S2CFRIENDLIST,
  __module__ = 'MessageFriend_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CFriendList)
  ))
_sym_db.RegisterMessage(S2CFriendList)

C2SAddFriend = _reflection.GeneratedProtocolMessageType('C2SAddFriend', (_message.Message,), dict(
  DESCRIPTOR = _C2SADDFRIEND,
  __module__ = 'MessageFriend_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SAddFriend)
  ))
_sym_db.RegisterMessage(C2SAddFriend)

C2SDeleteFriend = _reflection.GeneratedProtocolMessageType('C2SDeleteFriend', (_message.Message,), dict(
  DESCRIPTOR = _C2SDELETEFRIEND,
  __module__ = 'MessageFriend_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SDeleteFriend)
  ))
_sym_db.RegisterMessage(C2SDeleteFriend)


# @@protoc_insertion_point(module_scope)
