# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessagePlayer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessagePlayer.proto',
  package='Message',
  serialized_pb=_b('\n\x13MessagePlayer.proto\x12\x07Message\"A\n\x0f\x43\x32SPlayerCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\x12\x10\n\x08vocation\x18\x03 \x01(\x05\"\x1d\n\x0e\x43\x32SPlayerLogin\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"\x10\n\x0eS2CPlayerLogin')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2SPLAYERCREATE = _descriptor.Descriptor(
  name='C2SPlayerCreate',
  full_name='Message.C2SPlayerCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.C2SPlayerCreate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='Message.C2SPlayerCreate.gender', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vocation', full_name='Message.C2SPlayerCreate.vocation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=97,
)


_C2SPLAYERLOGIN = _descriptor.Descriptor(
  name='C2SPlayerLogin',
  full_name='Message.C2SPlayerLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.C2SPlayerLogin.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=128,
)


_S2CPLAYERLOGIN = _descriptor.Descriptor(
  name='S2CPlayerLogin',
  full_name='Message.S2CPlayerLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['C2SPlayerCreate'] = _C2SPLAYERCREATE
DESCRIPTOR.message_types_by_name['C2SPlayerLogin'] = _C2SPLAYERLOGIN
DESCRIPTOR.message_types_by_name['S2CPlayerLogin'] = _S2CPLAYERLOGIN

C2SPlayerCreate = _reflection.GeneratedProtocolMessageType('C2SPlayerCreate', (_message.Message,), dict(
  DESCRIPTOR = _C2SPLAYERCREATE,
  __module__ = 'MessagePlayer_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPlayerCreate)
  ))
_sym_db.RegisterMessage(C2SPlayerCreate)

C2SPlayerLogin = _reflection.GeneratedProtocolMessageType('C2SPlayerLogin', (_message.Message,), dict(
  DESCRIPTOR = _C2SPLAYERLOGIN,
  __module__ = 'MessagePlayer_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SPlayerLogin)
  ))
_sym_db.RegisterMessage(C2SPlayerLogin)

S2CPlayerLogin = _reflection.GeneratedProtocolMessageType('S2CPlayerLogin', (_message.Message,), dict(
  DESCRIPTOR = _S2CPLAYERLOGIN,
  __module__ = 'MessagePlayer_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CPlayerLogin)
  ))
_sym_db.RegisterMessage(S2CPlayerLogin)


# @@protoc_insertion_point(module_scope)
