# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageTypeDefine_pb2
import MessageCore_pb2
import MessageCommon_pb2
import MessageUser_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='',
  serialized_pb=_b('\n\x0b\x65vent.proto\x1a\x17MessageTypeDefine.proto\x1a\x11MessageCore.proto\x1a\x13MessageCommon.proto\x1a\x11MessageUser.proto\"\x9c\x01\n\x07\x46orward\x12\x14\n\x0cserveridFrom\x18\x01 \x01(\x05\x12\x12\n\nserveridTo\x18\x02 \x01(\x05\x12\x14\n\x0cserverfdFrom\x18\x03 \x01(\x05\x12\x12\n\nserverfdTo\x18\x04 \x01(\x05\x12\x14\n\x0c\x63lientfdFrom\x18\x05 \x01(\x05\x12\x12\n\nclientfdTo\x18\x06 \x01(\x05\x12\x13\n\x0bwebserverfd\x18\x07 \x01(\x05\"\x8b\x04\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x05\x12\x0b\n\x03uid\x18\x03 \x01(\x03\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12\x19\n\x07\x66orward\x18\x05 \x01(\x0b\x32\x08.Forward\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12+\n\x0c\x64senetaccept\x18\x64 \x01(\x0b\x32\x15.Message.DseNetAccept\x12-\n\rdsenetconnect\x18\x65 \x01(\x0b\x32\x16.Message.DseNetConnect\x12)\n\x0b\x64senetclose\x18\x66 \x01(\x0b\x32\x14.Message.DseNetClose\x12-\n\rdseserverinfo\x18g \x01(\x0b\x32\x16.Message.DseServerInfo\x12.\n\rdceguestlogin\x18\xe8\x07 \x01(\x0b\x32\x16.Message.DceGuestLogin\x12,\n\x0c\x64\x63\x65userlogin\x18\xe9\x07 \x01(\x0b\x32\x15.Message.DceUserLogin\x12.\n\rdceuserlogout\x18\xea\x07 \x01(\x0b\x32\x16.Message.DceUserLogout\x12,\n\x0c\x64\x63\x65userheart\x18\xeb\x07 \x01(\x0b\x32\x15.Message.DceUserHeart\x12,\n\x0c\x64seuserheart\x18\xec\x07 \x01(\x0b\x32\x15.Message.DseUserHeart')
  ,
  dependencies=[MessageTypeDefine_pb2.DESCRIPTOR,MessageCore_pb2.DESCRIPTOR,MessageCommon_pb2.DESCRIPTOR,MessageUser_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORWARD = _descriptor.Descriptor(
  name='Forward',
  full_name='Forward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serveridFrom', full_name='Forward.serveridFrom', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serveridTo', full_name='Forward.serveridTo', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverfdFrom', full_name='Forward.serverfdFrom', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverfdTo', full_name='Forward.serverfdTo', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientfdFrom', full_name='Forward.clientfdFrom', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientfdTo', full_name='Forward.clientfdTo', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='webserverfd', full_name='Forward.webserverfd', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=256,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Event.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='Event.state', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='Event.uid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='Event.time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forward', full_name='Event.forward', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Event.content', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsenetaccept', full_name='Event.dsenetaccept', index=6,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsenetconnect', full_name='Event.dsenetconnect', index=7,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsenetclose', full_name='Event.dsenetclose', index=8,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dseserverinfo', full_name='Event.dseserverinfo', index=9,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dceguestlogin', full_name='Event.dceguestlogin', index=10,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dceuserlogin', full_name='Event.dceuserlogin', index=11,
      number=1001, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dceuserlogout', full_name='Event.dceuserlogout', index=12,
      number=1002, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dceuserheart', full_name='Event.dceuserheart', index=13,
      number=1003, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dseuserheart', full_name='Event.dseuserheart', index=14,
      number=1004, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=782,
)

_EVENT.fields_by_name['forward'].message_type = _FORWARD
_EVENT.fields_by_name['dsenetaccept'].message_type = MessageCore_pb2._DSENETACCEPT
_EVENT.fields_by_name['dsenetconnect'].message_type = MessageCore_pb2._DSENETCONNECT
_EVENT.fields_by_name['dsenetclose'].message_type = MessageCore_pb2._DSENETCLOSE
_EVENT.fields_by_name['dseserverinfo'].message_type = MessageCore_pb2._DSESERVERINFO
_EVENT.fields_by_name['dceguestlogin'].message_type = MessageUser_pb2._DCEGUESTLOGIN
_EVENT.fields_by_name['dceuserlogin'].message_type = MessageUser_pb2._DCEUSERLOGIN
_EVENT.fields_by_name['dceuserlogout'].message_type = MessageUser_pb2._DCEUSERLOGOUT
_EVENT.fields_by_name['dceuserheart'].message_type = MessageUser_pb2._DCEUSERHEART
_EVENT.fields_by_name['dseuserheart'].message_type = MessageUser_pb2._DSEUSERHEART
DESCRIPTOR.message_types_by_name['Forward'] = _FORWARD
DESCRIPTOR.message_types_by_name['Event'] = _EVENT

Forward = _reflection.GeneratedProtocolMessageType('Forward', (_message.Message,), dict(
  DESCRIPTOR = _FORWARD,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:Forward)
  ))
_sym_db.RegisterMessage(Forward)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  ))
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
