# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTypeDefine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageTypeDefine.proto',
  package='Message',
  serialized_pb=_b('\n\x17MessageTypeDefine.proto\x12\x07Message*\xf3\x02\n\tMsgDefine\x12\r\n\tDSE_BEGIN\x10\x00\x12\x12\n\x0e\x44SE_NET_ACCEPT\x10\x01\x12\x13\n\x0f\x44SE_NET_CONNECT\x10\x02\x12\x11\n\rDSE_NET_CLOSE\x10\x03\x12\x13\n\x0f\x44SE_SERVER_INFO\x10\n\x12\x12\n\x0e\x44SE_SERVER_CMD\x10\x0b\x12\x14\n\x10\x44SE_COMMON_ERROR\x10\x14\x12\x12\n\x0e\x44SE_USER_HEART\x10\x64\x12\x14\n\x0f\x44SE_MESSAGE_END\x10\x87\'\x12\x16\n\x11\x44\x43\x45_MESSAGE_BEGIN\x10\x88\'\x12\x14\n\x0f\x44\x43\x45_GUEST_LOGIN\x10\x89\'\x12\x13\n\x0e\x44\x43\x45_USER_LOGIN\x10\x8a\'\x12\x14\n\x0f\x44\x43\x45_USER_LOGOUT\x10\x8b\'\x12\x13\n\x0e\x44\x43\x45_USER_HEART\x10\x8c\'\x12\x16\n\x11\x44\x43\x45_DEBUG_COMMAND\x10\x90N\x12\x16\n\x11\x44\x43\x45_DEBUG_NETTEST\x10\x91N\x12\x14\n\x0f\x44\x43\x45_MESSAGE_END\x10\x80P')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGDEFINE = _descriptor.EnumDescriptor(
  name='MsgDefine',
  full_name='Message.MsgDefine',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DSE_BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_NET_ACCEPT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_NET_CONNECT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_NET_CLOSE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_SERVER_INFO', index=4, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_SERVER_CMD', index=5, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_COMMON_ERROR', index=6, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_USER_HEART', index=7, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSE_MESSAGE_END', index=8, number=4999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_MESSAGE_BEGIN', index=9, number=5000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_GUEST_LOGIN', index=10, number=5001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_USER_LOGIN', index=11, number=5002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_USER_LOGOUT', index=12, number=5003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_USER_HEART', index=13, number=5004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_DEBUG_COMMAND', index=14, number=10000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_DEBUG_NETTEST', index=15, number=10001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DCE_MESSAGE_END', index=16, number=10240,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=37,
  serialized_end=408,
)
_sym_db.RegisterEnumDescriptor(_MSGDEFINE)

MsgDefine = enum_type_wrapper.EnumTypeWrapper(_MSGDEFINE)
DSE_BEGIN = 0
DSE_NET_ACCEPT = 1
DSE_NET_CONNECT = 2
DSE_NET_CLOSE = 3
DSE_SERVER_INFO = 10
DSE_SERVER_CMD = 11
DSE_COMMON_ERROR = 20
DSE_USER_HEART = 100
DSE_MESSAGE_END = 4999
DCE_MESSAGE_BEGIN = 5000
DCE_GUEST_LOGIN = 5001
DCE_USER_LOGIN = 5002
DCE_USER_LOGOUT = 5003
DCE_USER_HEART = 5004
DCE_DEBUG_COMMAND = 10000
DCE_DEBUG_NETTEST = 10001
DCE_MESSAGE_END = 10240


DESCRIPTOR.enum_types_by_name['MsgDefine'] = _MSGDEFINE


# @@protoc_insertion_point(module_scope)
