# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageCommon.proto',
  package='Message',
  serialized_pb=_b('\n\x13MessageCommon.proto\x12\x07Message\",\n\x0c\x44\x65\x62ugCommand\x12\x0f\n\x07strings\x18\x01 \x03(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x03\"8\n\x0c\x44\x65\x62ugNettest\x12\n\n\x02no\x18\x01 \x02(\x05\x12\r\n\x05idata\x18\x02 \x03(\x05\x12\r\n\x05sdata\x18\x03 \x01(\t\"\xe4\x01\n\x07\x45rrorNo\x12\r\n\x05\x65rror\x18\x01 \x01(\x05\x12\x0e\n\x06userid\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x11\n\tparamint1\x18\x04 \x01(\x05\x12\x11\n\tparamint2\x18\x05 \x01(\x05\x12\x11\n\tparamint3\x18\x06 \x01(\x05\x12\x12\n\nparamlong1\x18\x07 \x01(\x03\x12\x12\n\nparamlong2\x18\x08 \x01(\x03\x12\x12\n\nparamlong3\x18\t \x01(\x03\x12\x11\n\tparamstr1\x18\n \x01(\t\x12\x11\n\tparamstr2\x18\x0b \x01(\t\x12\x11\n\tparamstr3\x18\x0c \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEBUGCOMMAND = _descriptor.Descriptor(
  name='DebugCommand',
  full_name='Message.DebugCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strings', full_name='Message.DebugCommand.strings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.DebugCommand.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=76,
)


_DEBUGNETTEST = _descriptor.Descriptor(
  name='DebugNettest',
  full_name='Message.DebugNettest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='no', full_name='Message.DebugNettest.no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idata', full_name='Message.DebugNettest.idata', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdata', full_name='Message.DebugNettest.sdata', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=134,
)


_ERRORNO = _descriptor.Descriptor(
  name='ErrorNo',
  full_name='Message.ErrorNo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Message.ErrorNo.error', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='Message.ErrorNo.userid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.ErrorNo.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint1', full_name='Message.ErrorNo.paramint1', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint2', full_name='Message.ErrorNo.paramint2', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint3', full_name='Message.ErrorNo.paramint3', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong1', full_name='Message.ErrorNo.paramlong1', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong2', full_name='Message.ErrorNo.paramlong2', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong3', full_name='Message.ErrorNo.paramlong3', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr1', full_name='Message.ErrorNo.paramstr1', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr2', full_name='Message.ErrorNo.paramstr2', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr3', full_name='Message.ErrorNo.paramstr3', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=365,
)

DESCRIPTOR.message_types_by_name['DebugCommand'] = _DEBUGCOMMAND
DESCRIPTOR.message_types_by_name['DebugNettest'] = _DEBUGNETTEST
DESCRIPTOR.message_types_by_name['ErrorNo'] = _ERRORNO

DebugCommand = _reflection.GeneratedProtocolMessageType('DebugCommand', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGCOMMAND,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.DebugCommand)
  ))
_sym_db.RegisterMessage(DebugCommand)

DebugNettest = _reflection.GeneratedProtocolMessageType('DebugNettest', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGNETTEST,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.DebugNettest)
  ))
_sym_db.RegisterMessage(DebugNettest)

ErrorNo = _reflection.GeneratedProtocolMessageType('ErrorNo', (_message.Message,), dict(
  DESCRIPTOR = _ERRORNO,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.ErrorNo)
  ))
_sym_db.RegisterMessage(ErrorNo)


# @@protoc_insertion_point(module_scope)
