# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageCommon.proto',
  package='Message',
  serialized_pb=_b('\n\x13MessageCommon.proto\x12\x07Message\"\xe7\x01\n\nDseErrorNo\x12\r\n\x05\x65rror\x18\x01 \x01(\x05\x12\x0e\n\x06userid\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x11\n\tparamint1\x18\x04 \x01(\x05\x12\x11\n\tparamint2\x18\x05 \x01(\x05\x12\x11\n\tparamint3\x18\x06 \x01(\x05\x12\x12\n\nparamlong1\x18\x07 \x01(\x03\x12\x12\n\nparamlong2\x18\x08 \x01(\x03\x12\x12\n\nparamlong3\x18\t \x01(\x03\x12\x11\n\tparamstr1\x18\n \x01(\t\x12\x11\n\tparamstr2\x18\x0b \x01(\t\x12\x11\n\tparamstr3\x18\x0c \x01(\t\"\xa7\x01\n\x0b\x44seEventLog\x12\x0c\n\x04\x65vid\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\x03\x12\r\n\x05stime\x18\x03 \x01(\t\x12\x0e\n\x06param1\x18\x04 \x01(\x03\x12\x0e\n\x06param2\x18\x05 \x01(\x03\x12\x0e\n\x06param3\x18\x06 \x01(\x03\x12\x0e\n\x06param4\x18\x07 \x01(\x03\x12\x0e\n\x06param5\x18\x08 \x01(\x03\x12\x0e\n\x06param6\x18\t \x01(\x03\x12\x0e\n\x06param7\x18\n \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEERRORNO = _descriptor.Descriptor(
  name='DseErrorNo',
  full_name='Message.DseErrorNo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Message.DseErrorNo.error', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='Message.DseErrorNo.userid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.DseErrorNo.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint1', full_name='Message.DseErrorNo.paramint1', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint2', full_name='Message.DseErrorNo.paramint2', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramint3', full_name='Message.DseErrorNo.paramint3', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong1', full_name='Message.DseErrorNo.paramlong1', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong2', full_name='Message.DseErrorNo.paramlong2', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlong3', full_name='Message.DseErrorNo.paramlong3', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr1', full_name='Message.DseErrorNo.paramstr1', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr2', full_name='Message.DseErrorNo.paramstr2', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramstr3', full_name='Message.DseErrorNo.paramstr3', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=264,
)


_DSEEVENTLOG = _descriptor.Descriptor(
  name='DseEventLog',
  full_name='Message.DseEventLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evid', full_name='Message.DseEventLog.evid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.DseEventLog.uid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stime', full_name='Message.DseEventLog.stime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param1', full_name='Message.DseEventLog.param1', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='Message.DseEventLog.param2', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param3', full_name='Message.DseEventLog.param3', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param4', full_name='Message.DseEventLog.param4', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param5', full_name='Message.DseEventLog.param5', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param6', full_name='Message.DseEventLog.param6', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param7', full_name='Message.DseEventLog.param7', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=434,
)

DESCRIPTOR.message_types_by_name['DseErrorNo'] = _DSEERRORNO
DESCRIPTOR.message_types_by_name['DseEventLog'] = _DSEEVENTLOG

DseErrorNo = _reflection.GeneratedProtocolMessageType('DseErrorNo', (_message.Message,), dict(
  DESCRIPTOR = _DSEERRORNO,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.DseErrorNo)
  ))
_sym_db.RegisterMessage(DseErrorNo)

DseEventLog = _reflection.GeneratedProtocolMessageType('DseEventLog', (_message.Message,), dict(
  DESCRIPTOR = _DSEEVENTLOG,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.DseEventLog)
  ))
_sym_db.RegisterMessage(DseEventLog)


# @@protoc_insertion_point(module_scope)
