# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageUser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageUser.proto',
  package='Message',
  serialized_pb=_b('\n\x11MessageUser.proto\x12\x07Message\"-\n\rDceGuestLogin\x12\r\n\x05guest\x18\x01 \x01(\t\x12\r\n\x05world\x18\x02 \x01(\x05\"Y\n\x0c\x44\x63\x65UserLogin\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06ticket\x18\x02 \x01(\t\x12\r\n\x05world\x18\x03 \x01(\x05\x12\x0e\n\x06socket\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\x05\"\x1c\n\rDceUserLogout\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x0e\n\x0c\x44\x63\x65UserHeart\"\x1d\n\x0c\x44seUserHeart\x12\r\n\x05stime\x18\x01 \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUESTLOGIN = _descriptor.Descriptor(
  name='DceGuestLogin',
  full_name='Message.DceGuestLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guest', full_name='Message.DceGuestLogin.guest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Message.DceGuestLogin.world', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=75,
)


_DCEUSERLOGIN = _descriptor.Descriptor(
  name='DceUserLogin',
  full_name='Message.DceUserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.DceUserLogin.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='Message.DceUserLogin.ticket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Message.DceUserLogin.world', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='socket', full_name='Message.DceUserLogin.socket', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='Message.DceUserLogin.error', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=166,
)


_DCEUSERLOGOUT = _descriptor.Descriptor(
  name='DceUserLogout',
  full_name='Message.DceUserLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.DceUserLogout.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=196,
)


_DCEUSERHEART = _descriptor.Descriptor(
  name='DceUserHeart',
  full_name='Message.DceUserHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=212,
)


_DSEUSERHEART = _descriptor.Descriptor(
  name='DseUserHeart',
  full_name='Message.DseUserHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stime', full_name='Message.DseUserHeart.stime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=243,
)

DESCRIPTOR.message_types_by_name['DceGuestLogin'] = _DCEGUESTLOGIN
DESCRIPTOR.message_types_by_name['DceUserLogin'] = _DCEUSERLOGIN
DESCRIPTOR.message_types_by_name['DceUserLogout'] = _DCEUSERLOGOUT
DESCRIPTOR.message_types_by_name['DceUserHeart'] = _DCEUSERHEART
DESCRIPTOR.message_types_by_name['DseUserHeart'] = _DSEUSERHEART

DceGuestLogin = _reflection.GeneratedProtocolMessageType('DceGuestLogin', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUESTLOGIN,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.DceGuestLogin)
  ))
_sym_db.RegisterMessage(DceGuestLogin)

DceUserLogin = _reflection.GeneratedProtocolMessageType('DceUserLogin', (_message.Message,), dict(
  DESCRIPTOR = _DCEUSERLOGIN,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.DceUserLogin)
  ))
_sym_db.RegisterMessage(DceUserLogin)

DceUserLogout = _reflection.GeneratedProtocolMessageType('DceUserLogout', (_message.Message,), dict(
  DESCRIPTOR = _DCEUSERLOGOUT,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.DceUserLogout)
  ))
_sym_db.RegisterMessage(DceUserLogout)

DceUserHeart = _reflection.GeneratedProtocolMessageType('DceUserHeart', (_message.Message,), dict(
  DESCRIPTOR = _DCEUSERHEART,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.DceUserHeart)
  ))
_sym_db.RegisterMessage(DceUserHeart)

DseUserHeart = _reflection.GeneratedProtocolMessageType('DseUserHeart', (_message.Message,), dict(
  DESCRIPTOR = _DSEUSERHEART,
  __module__ = 'MessageUser_pb2'
  # @@protoc_insertion_point(class_scope:Message.DseUserHeart)
  ))
_sym_db.RegisterMessage(DseUserHeart)


# @@protoc_insertion_point(module_scope)
